version: "3.4"
services:
  validator-test.public.dappnode.eth:
    build: .
    image: "validator-test.public.dappnode.eth:0.1.20"
    restart: unless-stopped
    volumes:
      - "val_data:/var/data"
    environment:
      - EXTRA_OPTS=
    ports:
      - "2154:2154"
volumes:
  val_data: {}
